### ISSUE TITLE
Allow additional options

### ISSUE THREAD

**Issue by roaldnefs** [roaldnefs/salt-lint-action#1]
Currently the salt-lint-action doesn't allow you to run salt-lint with additional options, but [salt-lint](https://github.com/roaldnefs/salt-lint) does include several [command line options](https://github.com/roaldnefs/salt-lint#command-line-options).

**Possible Solution:**
Add the [command line options](https://github.com/roaldnefs/salt-lint#command-line-options) as [Github Action inputs](https://help.github.com/en/articles/metadata-syntax-for-github-actions#inputs).

**Comment by dyllew3** [comment]
I'd be willing to take a swing at it.

**Comment by roaldnefs** [comment]
Thanks @dyllew3, I've assigned you to this issue. Let me know if you have any questions!
